# Generated by Django 3.2.4 on 2022-06-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20220622_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitem',
            old_name='customer_id',
            new_name='invoice_id',
        ),
    ]
