# Generated by Django 3.2.4 on 2022-06-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_lineitem_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='pid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
