# Generated by Django 3.2.4 on 2022-06-22 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20220622_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitem',
            old_name='id',
            new_name='pid',
        ),
        migrations.RemoveField(
            model_name='lineitemindi',
            name='service_serialnumber',
        ),
        migrations.AddField(
            model_name='lineitemindi',
            name='pid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoice.lineitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineitemindi',
            name='serial_number',
            field=models.CharField(default=122, max_length=100),
            preserve_default=False,
        ),
    ]
