# Generated by Django 3.2.4 on 2022-06-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20220622_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='pid',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
